//
//  CollectionViewCell.swift
//  Dogs
//
//  Created by Anuraag Shakya on 31.07.18.
//  Copyright © 2018 Bhunte. All rights reserved.
//

import UIKit

class CollectionViewCell: UICollectionViewCell {
    
    @IBOutlet weak var imageView: UIImageView!
    
    // Variable to store URLSessionTask we use to fetch the cell's image.
    var task: URLSessionTask?
    
    // urlString parameter that holds the image URL and calls the
    //  fetchImageFromUrl method when set.
    var urlString: String! {
        didSet {
            self.imageView.image = nil
            fetchImageFromUrl(self.urlString)
        }
    }
    
    // TODO: Create an image cache of downloaded images to minimize network
    //  operation.
    
    private func fetchImageFromUrl(_ urlString: String) {
        guard let url = URL(string: urlString) else {
            print("Invalid image URL \(urlString)")
            return
        }
        
        // Cancel any previous image fetching task. Then create a new task to
        //  fetch current image.
        task?.cancel()
        task = URLSession.shared.dataTask(with: url) { (data, response, error) in
            
            guard let data = data, error == nil else {
                // Print all error codes except those generated by cancelling
                //  a URLSessionTask so that it does not spam the debug output.
                if error!._code != -999 {
                    let customError = ErrorResult.network(string: error!.localizedDescription)
                    print(customError.description())
                }
                return
            }
            
            // Set the cells image to what we get from url on main queue
            DispatchQueue.main.async {
                self.imageView.image = UIImage(data: data)
            }
        }
        task!.resume()
    }
    
}
