//
//  CollectionViewCell.swift
//  Dogs
//
//  Created by Anuraag Shakya on 31.07.18.
//  Copyright © 2018 Bhunte. All rights reserved.
//

import UIKit

class CollectionViewCell: UICollectionViewCell {
    
    @IBOutlet weak var imageView: UIImageView!
    
    var task: URLSessionTask?
    
    var urlString: String! {
        didSet {
            self.imageView.image = nil
            fetchImageFromUrl(self.urlString)
        }
    }
    
    override func awakeFromNib() {
        self.layer.cornerRadius = 10
    }
    
    func fetchImageFromUrl(_ urlString: String) {
        guard let url = URL(string: urlString) else {
            return
        }
        task?.cancel()
        task = URLSession.shared.dataTask(with: url) { (data, response, error) in
            
            guard let data = data, error == nil else {
                let customError = ErrorResult.network(string: error!.localizedDescription)
                // Print all error codes except those generated by cancelling
                //  a URLSessionTask
                if error!._code != -999 {
                    print(customError.description())
                }
                return
            }
            
            DispatchQueue.main.async {
                self.imageView.image = UIImage(data: data)
            }
        }
        task!.resume()
    }
    
}
